version: "3.8"
services:
  yolo5:
    container_name: yolo5-web
    image: yolo5:1.1
    networks:
      - docker_network
    ports:
      - "8081:8081"
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
    environment:
      BUCKET_NAME: $BUCKET_NAME
      MONGO_USER: $MONGO_USER
      MONGO_PASS: $MONGO_PASS
    env_file:
      - .env
  polybot:
    container_name: poly-web
    image: poly:1.1
    networks:
      - docker_network
    ports:
      - "8443:8443"
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
    environment:
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
      BUCKET: $BUCKET
      BUCKET_FOLDER: $BUCKET_FOLDER

    env_file:
      - .env
networks:
  docker_network:
    driver: bridge







